# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0009_auto_20170422_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='TIL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(to='blog.Tag')),
            ],
        ),
    ]
