version: '3.2'

services:
    db:
      image: postgres:9.6
      volumes:
          - postgres-data:/var/lib/postgresql/data

    server:
      build:
        context: ./
      env_file:
          - .env
      command: bash -c '/code/scripts/wait-for-it.sh db:5432 && /code/scripts/run_develop.sh'
      volumes:
          - ./:/code
          - media:/media
          - ./static:/static
      ports:
          - '8009:8009'
      depends_on:
          - db

volumes:
  media:
  postgres-data:
