version: '3.2'

services:
    db:
        image: postgres:9.6
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - ./postgres-data:/var/lib/postgres/data
        ports:
            - '5432:5432'
