# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 10:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_markdown.models.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 4, 10, 23, 21, 164898)),
        ),
    ]
