# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 03:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170209_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 10, 3, 58, 33, 440901)),
        ),
    ]
